alter table USER drop constraint UK_r61ihmpmuedleishhqfatav3x;
alter table USER drop constraint UK_f2eme58cb7sw3hj6rfqn6hmw9;
alter table APP drop constraint FK3a81gkamtyuunogpqfxl916la;
alter table APP_CONTETN_TYPE drop constraint FKi0qt7pcceux6rno9do2qcsq5n;

drop table APP if exists;
drop table APP_CONTETN_TYPE if exists;
drop table USER if exists;

create table APP (
  id integer generated by default as identity (start with 1),
  APP_NAME varchar(255) not null,
  APP_TYPE varchar(255) not null,
  USER_ID integer,
  primary key (id)
);

create table APP_CONTETN_TYPE (
  App_id integer not null,
  CONTETN_TYPE varchar(255)
);

create table USER (
  DTYPE varchar(31) not null,
  id integer generated by default as identity (start with 1),
  USER_MAIL varchar(255) not null,
  USER_NAME varchar(255) not null,
  SEC_USER_LOGIN varchar(255) not null,
  SEC_USER_PASSWORD varchar(255) not null,
  SEC_USER_ROLE varchar(255) not null,
  primary key (id)
);

alter table USER add constraint UK_r61ihmpmuedleishhqfatav3x unique (USER_MAIL);
alter table USER add constraint UK_f2eme58cb7sw3hj6rfqn6hmw9 unique (SEC_USER_LOGIN);
alter table APP add constraint FK3a81gkamtyuunogpqfxl916la foreign key (USER_ID) references USER;
alter table APP_CONTETN_TYPE add constraint FKi0qt7pcceux6rno9do2qcsq5n foreign key (App_id) references APP;